name: Frontend Test

on: push

defaults:
  run:
    shell: bash
    working-directory: functions

jobs:
  test:
    name: jest
    runs-on: ubuntu-latest
    steps:
    - run: node -v
    - name: Set up Repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: node -v
    - run: yarn -v
    - run: yarn install
    - run: yarn test
