name: Frontend Test

on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    name: jest
    runs-on: ubuntu-latest
    steps:
    - name: Set up Repository
      uses: actions/checkout@v2
    - run: node -v
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: node -v
    - run: yarn -v
    - name: Exec Test
      working-directory: ./functions
      run: yarn install && yarn test
